config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do |map|
  resources :projects do
    get 'test_cases/auto_complete', to: 'test_cases#auto_complete', as: 'auto_complete_test_cases'

    get 'test_plans/statistics', to: 'test_plans#statistics', as: 'test_plan_statistics'
    get 'test_cases/statistics', to: 'test_cases#statistics', as: 'test_case_statistics'

    match 'test_cases/context_menu', :to => 'test_cases#list_context_menu', :as => :test_case_list_context_menu, :via => [:get, :post]
    resources :test_cases do
      resources :test_case_executions
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
      #match 'context_menu', :to => 'test_cases#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
    end

    match 'test_plans/context_menu', :to => 'test_plans#list_context_menu', :as => :test_plan_list_context_menu, :via => [:get, :post]
    resources :test_plans do
      resources :test_cases do
        resources :test_case_executions
      end

      resources :test_case_executions

      post 'assign_test_case', to: 'test_plans#assign_test_case'
      delete 'assign_test_case/:id', to: 'test_plans#unassign_test_case'
      delete 'assign_test_case', to: 'test_plans#unassign_test_case'

      match 'context_menu', :to => 'test_plans#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end

    match 'test_case_executions/context_menu', :to => 'test_case_executions#list_context_menu', :as => :test_case_execution_list_context_menu, :via => [:get, :post]
    resources :test_case_executions do
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end
  end

  get 'projects/:project_id/test_cases/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseImport'},
      :as => 'new_test_cases_import'

  get 'projects/:project_id/test_plans/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestPlanImport'},
      :as => 'new_test_plans_import'

  get 'projects/:project_id/test_case_executions/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseExecutionImport'},
      :as => 'new_test_case_executions_import'
end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
  include Redmine::SafeAttributes
  include TestCaseManagement::SafeAttributes
  include TestCaseManagement::InheritIssuePermissions

  belongs_to :user
  belongs_to :project
  has_many :test_case_test_plans, dependent: :destroy
  has_many :test_plans, through: :test_case_test_plans
  has_many :test_case_executions, dependent: :destroy
  acts_as_attachable

  validates :name, presence: true
  validates :scenario, presence: true
  validates :expected, presence: true
  validates :user, presence: true
  validates :project, presence: true

  validates_associated :test_case_executions

  validate :owned_only_by_visible_user

  safe_attributes(
    "project_id",
    "user_id",
    "name",
    "environment",
    "scenario",
    "expected",
    :if => lambda {|instance, user| instance.new_record? || instance.attributes_editable?(user)})

  def safe_attribute_names(user=nil)
    names = super
    if new_record?
      names |= %w(project_id)
    end
    names
  end

  scope :visible, (lambda do |*args|
    joins(:project).
    where(TestCaseManagement::InheritIssuePermissions.visible_condition(args.shift || User.current, *args))
  end)

  scope :with_latest_result, (lambda do |test_plan_or_id=nil, for_count=false|
    test_plan_id = test_plan_or_id
    test_plan_id = test_plan_or_id.id if test_plan_or_id.is_a?(TestPlan)
    test_plan_id = nil unless test_plan_id.is_a?(Integer)

    scope = all
    conditions = {}
    if test_plan_id
      scope = scope.
        joins(:test_case_test_plans)
      conditions["test_case_test_plans.test_plan_id"] = test_plan_id
    end

    scope = scope.
    joins(<<-"SQL"
      LEFT OUTER JOIN
        (SELECT *
           FROM (SELECT *,
                        ROW_NUMBER()
                          OVER (PARTITION BY test_case_id
                                ORDER BY execution_date DESC, id DESC)
                          AS row_number_per_test_case_id
                   FROM test_case_executions
                   #{ test_plan_id ? sanitize_sql_array(['WHERE test_plan_id = ?', test_plan_id]) : '' })
                 AS tce_with_row_number
          WHERE row_number_per_test_case_id = 1) AS tce
        ON tce.test_case_id = test_cases.id
        #{ test_plan_id ? 'AND tce.test_plan_id = test_case_test_plans.test_plan_id' : '' }
SQL
    ).
    where(conditions)
    # Avoid syntax error with count()
    if for_count
      if Redmine::Database.postgresql?
        scope.select("test_cases.*")
      else
        scope.select("*")
      end
    else
      scope.select(<<-SQL
        test_cases.*,
        tce.id AS latest_execution_id,
        tce.result AS latest_result,
        tce.execution_date AS latest_execution_date
SQL
    )
    end
  end)

  class << self
    def find_with_latest_result(id, options={})
      with_latest_result(options[:test_plan] || options[:test_plan_id]).find(id)
    end
  end

  # attributes based on most recently executed result
  def latest_result
    value = attributes["latest_result"]
    if value.is_a?(Integer) # SQLite
      attributes["latest_result"] = value == 1
    else # PostgreSQL and others
      value
    end
  end

  def latest_execution_date
    value = attributes["latest_execution_date"]
    if value.is_a?(String) # SQLite
      attributes["latest_execution_date"] = Time.parse(value)
    else # PostgreSQL and others
      value
    end
  end

  def latest_test_case_execution
    if attributes["latest_execution_id"]
      TestCaseExecution.find(attributes["latest_execution_id"])
    else
      nil
    end
  end

  def test_case_executions_for(test_plan=self.test_plan)
    conditions = {test_case: self}
    if test_plan
      if test_plan.is_a?(TestPlan)
        conditions[:test_plan] = test_plan
      else
        conditions[:test_plan_id] = test_plan
      end
    end
    TestCaseExecution
      .where(conditions)
  end


  def attachments_visible?(user=User.current)
    visible?(user)
  end

  def attachments_editable?(user=User.current)
    editable?(user)
  end

  def attachments_deletable?(user=User.current)
    deletable?(user)
  end


  # Workaround for functional tests.
  # This should be removed after we completely migrate to test_plan-independent design.
  def test_plan
    test_plans.first
  end
end

app/models/test_case_execution.rb
class TestCaseExecution < ActiveRecord::Base
  include Redmine::SafeAttributes
  include TestCaseManagement::SafeAttributes
  include TestCaseManagement::InheritIssuePermissions

  belongs_to :user
  belongs_to :project
  belongs_to :issue
  belongs_to :test_plan
  belongs_to :test_case
  acts_as_attachable

  validates :result, inclusion: { in: [true, false] }
  validates :user, presence: true
  validates :test_plan, presence: true
  validates :test_case, presence: true
  validates :execution_date, presence: true

  validate :owned_only_by_visible_user

  safe_attributes(
    "project_id",
    "name",
    "issue_id",
    "user_id",
    "test_case_id",
    "test_plan_id",
    "result",
    "comment",
    "execution_date",
    :if => lambda {|instance, user| instance.new_record? || instance.attributes_editable?(user)})

  def safe_attribute_names(user=nil)
    names = super
    if new_record?
      names |= %w(project_id)
    end
    names
  end

  scope :visible, (lambda do |*args|
    joins(:project).
    where(TestCaseManagement::InheritIssuePermissions.visible_condition(args.shift || User.current, *args))
  end)

  def attachments_visible?(user=User.current)
    visible?(user)
  end

  def attachments_editable?(user=User.current)
    editable?(user)
  end

  def attachments_deletable?(user=User.current)
    deletable?(user)
  end
end

app/helpers/test_case_executions_helper.rb
module TestCaseExecutionsHelper
  include ApplicationsHelper

  def test_case_destroy_confirmation_message(test_case_execution)
    message = "#{test_case_execution.test_case.name}\n"
    message << l(:text_test_case_execution_destroy_confirmation)
    message
  end

  def breadcrumb
    links = []

    if @test_plan_given
      links << link_to(l(:label_test_plans),
                       project_test_plans_path)
      links << "&#187;"
      if @test_plan
        links << link_to("##{@test_plan.id} #{@test_plan.name}",
                         project_test_plan_path(id: @test_plan.id))
        links << "&#187;"
        if @test_case_given and @test_case
          links << link_to("#{l(:label_test_cases)} ##{@test_case.id} #{@test_case.name}",
                           project_test_plan_test_case_path(test_plan_id: @test_plan.id,
                                                            id: @test_case.id))
          links << "&#187;"
        end
      end
      links << ""
    elsif @test_case_given
      links << link_to(l(:label_test_cases),
                       project_test_cases_path)
      links << "&#187;"
      if @test_case
        links << link_to("##{@test_case.id} #{@test_case.name}",
                         project_test_case_path(id: @test_case.id))
        links << "&#187;"
      end
      links << ""
    end

    links.join(" ").html_safe
  end
end

app/views/test_case_executions/_action_menu.html.erb
<div class="contextual">
  <% if @test_case_execution %>
    <%= link_to l(:button_list),
                project_test_plan_test_case_test_case_executions_path,
                class: 'icon icon-list' %>
    <%= link_to l(:button_edit), edit_project_test_plan_test_case_test_case_execution_path,
        :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
    :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @test_case_execution.editable? %>
    <%= link_to l(:button_delete), project_test_plan_test_case_test_case_execution_path,
        :data => {:confirm => test_case_destroy_confirmation_message(@test_case_execution)},
    :method => :delete, :class => 'icon icon-del' if @test_case_execution.deletable? %>
  <% end %>
</div>

app/views/test_case_executions/_form.html.erb
<div class="box tabular">
  <p>
    <%= form.label :test_plan %>
    <%= (@test_plan || @test_case_execution.test_plan).name %>
  </p>
  <p>
    <%= form.label :test_case %>
    <%= (@test_case || @test_case_execution.test_case).name %>
  </p>
  <p>
    <%= form.label :environment %>
    <%= @test_case.environment %>
  </p>
  <p>
    <%= form.label :scenario %>
    <%= form.text_area :scenario, readonly: true, id: "scenario",
        cols: 60, rows: [[10, @test_case.scenario.to_s.length / 50].max, 20].min,
        value: @test_case.scenario %>
  </p>
  <p>
    <%= form.label :expected %>
    <%= form.text_area :expected, readonly: true, id: "expected",
        cols: 60, rows: [[10, @test_case.expected.to_s.length / 50].max, 20].min,
        value: @test_case.expected %>
  </p>
  <p>
    <%= form.label :result %>
    <% if action_name == "edit" %>
      <%= form.select :result, { l(:label_succeed) => true,l(:label_failure) => false }%>
    <% else %>
      <%= form.select :result, { l(:label_succeed) => true,l(:label_failure) => false }, selected: l(:label_succeed) %>
    <% end %>
  </p>
  <p>
    <%= form.label :user %>
    <% if @test_case_execution and @test_case_execution.user %>
      <%= form.select :user, @user_candidates, selected: @test_case_execution.user.id %>
    <% else %>
      <%= form.select :user, @user_candidates %>
    <% end %>
  </p>
  <p>
    <%= form.label :execution_date %>
    <%= form.date_field :execution_date,
        value: (@test_case_execution.execution_date ? @test_case_execution.execution_date.strftime("%F") : Time.now.strftime("%F")), required: true %>
  </p>
  <p>
    <%= form.label :issue %>
    <%= form.text_field :issue_id, id: 'issue_id' %>
    <%= link_to l(:label_issue_new),
                @issue_template_uri,
                :target => "_blank",
                :class => "icon icon-add new-issue" %>
  </p>
  <p>
    <%= form.label :comment %>
    <%= form.text_area :comment,
        cols: 60, rows: [[10, @test_case.expected.to_s.length / 50].max, 20].min %>
  </p>
</div>

<div class="box">
  <p>
    <%= form.label l :label_attachment_plural %>
    <%= render partial: 'attachments/form' %>
  </p>
</div>

<%= javascript_tag "observeAutocompleteField('issue_id', '#{escape_javascript auto_complete_issues_path(project_id: @project, issue_id: @test_case_execution.issue_id)}')" %>

app/views/test_case_executions/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<%= form_tag({}, :data => {:cm_url => project_test_case_execution_list_context_menu_path}) do -%>
  <%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>
  <%= query_columns_hidden_tags(query) %>
  <div class="autoscroll">
  <table id="test_case_executions_list" class="list test_case_executions odd-even <%= query.css_classes %>">
    <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% query.inline_columns.each do |column| %>
          <%= column_header(query, column, query_options) %>
        <% end %>
        <th class="buttons"></th>
      </tr>
    </thead>
    <tbody>
      <% test_case_executions.each do |test_case_execution| -%>
        <tr id="test-case-execution-<%= test_case_execution.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", test_case_execution.id, false, id: nil) %></td>
          <% query.inline_columns.each do |column| %>
            <% if [:scenario, :expected, :test_case].include?(column.css_classes) %>
              <%= content_tag('td', column_content(column, test_case_execution), :class => column.css_classes, :style => "text-align: left;") %>
            <% else %>
              <%= content_tag('td', column_content(column, test_case_execution), :class => column.css_classes) %>
            <% end %>
          <% end %>
          <td class="buttons"><%= link_to_context_menu %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  </div>
<% end -%>

<% context_menu %>

app/views/test_case_executions/_sidebar.html.erb
<h3><%= l(:label_testcase_management) %></h3>

<ul>
  <li><%= link_to l(:label_test_cases), project_test_cases_path %></li>
  <li><%= link_to l(:label_test_plans), project_test_plans_path %></li>
  <li><%= link_to l(:label_test_case_executions),
                  project_test_case_executions_path %></li>
</ul>

<h3><%= l(:label_statistics) %></h3>

<ul>
  <li><%= link_to l(:label_test_plan_statistics), project_test_plan_statistics_path, class: 'icon icon-stats' %></li>
  <li><%= link_to l(:label_test_case_statistics), project_test_case_statistics_path, class: 'icon icon-stats' %></li>
</ul>

<%= call_hook(:view_test_case_executions_sidebar_bottom) %>

<% if controller.action_name == "index" %>
  <%= render_sidebar_queries(TestCaseExecutionQuery, @project) %>
  <%= call_hook(:view_test_case_executions_sidebar_queries_bottom) %>
<% end %>

app/views/test_case_executions/bulk_edit.html.erb
<h2><%= l(:label_bulk_edit_selected_test_case_executions) %></h2>

<% if @saved_test_case_executions && @unsaved_test_case_executions.present? %>
<div id="errorExplanation">
  <span>
    <%= l(:notice_failed_to_save_test_case_executions,
        :count => @unsaved_test_cases.size,
        :total => @saved_test_cases.size,
        :ids => @unsaved_test_cases.map {|i| "##{i.id}"}.join(', ')) %>
  </span>
  <ul>
  <% bulk_edit_error_messages(@unsaved_test_case_executions).each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<ul id="bulk-selection">
  <% @test_case_executions.each do |test_case_execution| %>
    <%= content_tag 'li', link_to("#{test_case_execution.id}", project_test_case_execution_path(id: test_case_execution.id)) %>
  <% end %>
</ul>

<%= form_tag(bulk_update_project_test_case_executions_path(back: @back_url), :id => 'bulk_edit_form') do %>
  <%= hidden_field_tag('back_url', @back_url) %>
  <%= @test_case_executions.collect {|i| hidden_field_tag('ids[]', i.id, :id => nil)}.join("\n").html_safe %>
  <div class="box tabular">
    <fieldset class="attributes">
      <legend><%= l(:label_change_properties) %></legend>

      <div class="splitcontent">
        <div class="splitcontentleft">
          <% if @safe_attributes.include?('environment') -%>
          <p>
            <label for='test_case_environment'><%= l(:field_environment) %></label>
            <%= text_field_tag "test_case[environment]", nil, size:60, id: "environment" %>
          </p>
          <% end %>
        </div>
        <div class="splitcontentleft">
          <% if @safe_attributes.include?('user_id') -%>
          <p>
            <label for='test_case_execution_user_id'><%= l(:field_user) %></label>
            <%= select_tag('test_case_execution[user_id]',
                content_tag('option', l(:label_no_change_option), :value => '') +
            principals_options_for_select(@assignables, @test_case_execution_params[:user_id])) %>
          </p>
          <% end %>
        </div>

        <div class="splitcontentleft">
          <% if @safe_attributes.include?('execution_date') %>
          <p>
            <label for='test_case_execution_execution_date'><%= l(:field_execution_date) %></label>
            <%= date_field_tag 'test_case_execution[execution_date]', '', :value => @test_case_execution_params[:execution_date], :size => 10 %><%= calendar_for('test_case_execution_execution_date') %>
            <label class="inline"><%= check_box_tag 'test_case_execution[execution_date]', 'none', (@test_case_execution_params[:execution_date] == 'none'), :id => nil, :data => {:disables => '#test_case_execution_date'} %><%= l(:button_clear) %></label>
          </p>
          <% end %>
        </div>

        <div class="splitcontentright">
        </div>
      </div>
    </fieldset>
  </div>
  <p>
    <%= submit_tag l(:button_submit) %>
  </p>
<% end %>

<%= javascript_tag do %>
$(window).on('load', function(){
  $(document).on('change', 'input[data-disables]', function(){
    if ($(this).prop('checked')){
      $($(this).data('disables')).attr('disabled', true).val('');
    } else {
      $($(this).data('disables')).attr('disabled', false);
    }
  });
});
$(document).ready(function(){
  $('input[data-disables]').trigger('change');
});
<% end %>

app/views/test_case_executions/edit.html.erb
<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_case_execution_edit)%> #<%= @test_case_execution.id %></h2>

<%= form_with(model: @test_case_execution,
              url: (@test_plan_given ? project_test_plan_test_case_test_case_execution_path : project_test_case_test_case_execution_path),
              html: { multipart: true }) do |f| %>
  <%= render partial: 'test_case_executions/form', locals: {form: f} %>
  <%= f.submit l(:button_update) %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_case_executions/sidebar' %>
<% end %>

app/views/test_case_executions/forbidden.html.erb
<% if @project and @test_plan and @test_case %>
  <%= link_to l(:label_back_to_lists), project_test_plan_test_case_test_case_executions_path %>
<% elsif @project and @test_plan %>
  <%= link_to l(:label_back_to_lists), project_test_plan_test_cases_path %>
<% elsif @project and @toplevel_test_case_execution %>
  <%= link_to l(:label_back_to_lists), project_test_case_executions_path %>
<% elsif @project %>
  <%= link_to l(:label_back_to_lists), project_test_plans_path %>
<% else %>
  <%= link_to l(:label_back_to_lists), projects_path %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_case_executions/sidebar' %>
<% end %>

app/views/test_case_executions/index.html.erb
<div class="contextual">
  <% if @test_plan_given and @test_case_given %>
    <%= link_to l(:label_test_case_execution_new),
                new_project_test_plan_test_case_test_case_execution_path,
                :class => "icon icon-add new-issue" %>
  <% end %>
  <%= actions_dropdown do %>
    <% if User.current.allowed_to?(:add_test_case_executions, @project, :global => true) %>
      <%= link_to l(:button_import),
                  new_test_case_executions_import_path(:project_id => @project),
                  :class => "icon icon-import" %>
    <% end %>
  <% end %>
</div>

<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_case_executions)%></h2>

<%= form_tag((@test_plan_given and @test_case_given) ? project_test_plan_test_case_test_case_executions_path :
              @test_case_given ? project_test_case_test_case_executions_path :
              @test_plan_given ? project_test_plan_test_case_executions_path :
              project_test_case_executions_path,
             :method => :get, :id => 'query_form') do %>
  <%= render :partial => 'queries/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @test_case_executions.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'test_case_executions/list', :locals => {:test_case_executions => @test_case_executions, :query => @query} %>
    <span class="pagination"><%= pagination_links_full @test_case_execution_pages, @test_case_execution_count %></span>
  <% end %>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters 'CSV', {}, :onclick => "showModal('csv-export-options', '350px'); return false;" %>
<% end %>

<div id="csv-export-options" style="display:none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= form_tag(@csv_url, :method => :get, :id => 'csv-export-form') do %>
  <%= query_as_hidden_field_tags(@query) %>
  <%= export_csv_encoding_select_tag %>
  <% if @test_case_execution_count > @test_case_executions_export_limit %>
  <p class="icon icon-warning">
    <%= l(:settings_test_case_executions_export_limit) %>: <%= @test_case_executions_export_limit %>
  </p>
  <% end %>
  <p class="buttons">
    <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);", :data => { :disable_with => false } %>
    <%= link_to_function l(:button_cancel), "hideModal(this);" %>
  </p>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render :partial => 'test_case_executions/sidebar' %>
<% end %>

app/views/test_case_executions/list_context_menu.html.erb
<ul>
  <% if @test_case_execution %>
    <li><%= context_menu_link l(:button_edit),
            edit_project_test_plan_test_case_test_case_execution_path(test_plan_id: @test_case_execution.test_plan.id,
            test_case_id: @test_case_execution.test_case.id, id: @test_case_execution.id),
            class: 'icon icon-edit', disabled: !@can[:edit] %></li>
  <% else %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_project_test_case_executions_path(:ids => @test_case_execution_ids, :back_url => @back),
      :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
  <% end %>
  <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_user) %></a>
      <ul>
        <% if @assignables.include?(User.current) %>
        <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_case_executions_path(:ids => @test_case_execution_ids, :test_case_execution => {'user_id' => User.current},
          :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
        <% end %>
        <% @assignables.each do |u| -%>
        <li><%= context_menu_link u.name, bulk_update_project_test_case_executions_path(:ids => @test_case_execution_ids, :test_case_execution => {'user_id' => u}, :back_url => @back),
          :method => :post, :disabled => !@can[:edit] %></li>
        <% end -%>
      </ul>
    </li>
    <% end %>
  <li class="folder">
    <a href="#" class="submenu"><%= l(:field_result) %></a>
    <ul>
      <% [{name: l(:label_succeed), value: 1},
         {name: l(:label_failure), value: 0}].each do |status| -%>
      <li><%= context_menu_link status[:name], bulk_update_project_test_case_executions_path(:ids => @test_case_execution_ids, :test_case_execution => {'result' => status[:value]}, :back_url => @back),
        :method => :post, :disabled => !@can[:edit] %></li>
      <% end -%>
    </ul>
  </li>
  <% ids = @test_case_executions.pluck(:id).map { |id| "ids[]=#{id}" }.join("&") %>
  <li><%= link_to l(:button_delete),
          bulk_delete_project_test_case_executions_path(:ids => @test_case_execution_ids, :back_url => @back),
    method: :delete,
    data: { confirm: l(:text_are_you_sure) },
    title: l(:button_delete),
    class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
</ul>

app/views/test_case_executions/new.html.erb
<h2 class="inline-flex"><%= breadcrumb %><%= l(:label_test_case_execution_new) %></h2>

<%= form_with model: @test_case_execution, url: project_test_plan_test_case_test_case_executions_path do |f| %>
  <%= render partial: 'test_case_executions/form', locals: {form: f} %>
  <%= f.submit l(:button_create) %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_case_executions/sidebar' %>
<% end %>

app/views/test_case_executions/show.html.erb
<%= render :partial => 'action_menu', :locals => {:project_id => @project.name } %>

<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_case_executions)%> #<%= @test_case_execution.id %></h2>

<div class="issue details">
  <div class="subject">
    <div>
      <h3><%= @test_case.name %> <%=l(:field_result) %></h3>
    </div>
  </div>
  <div class="attributes">
    <div class="splitcontent">
      <div class="splitcontentleft">
        <div class="status attribute">
          <div class="label"><%=l(:field_test_plan)%></div>
          <div id="test_plan" class="value"><%= link_to @test_plan.name, project_test_plan_path(:project_id => @project.name, :id => @test_plan.id) %></div>
        </div>
        <div class="status attribute">
          <div class="label"><%=l(:field_test_case)%></div>
          <div id="test_case" class="value"><%= link_to @test_case.name, project_test_plan_test_case_path(:project_id => @project.name, :id => @test_case.id) %></div>
        </div>
        <div class="assigned-to attribute">
          <div class="label"><%=l(:field_user)%></div>
          <div id="user" class="value"><%= @test_case_execution.user.name if @test_case_execution.user %></div>
        </div>
      </div>
      <div class="splitcontentleft">
        <div class="result attribute">
          <div class="label"><%=l(:field_result)%></div>
          <div id="result" class="value">
            <% if @test_case_execution.result %>
              <%= l(:label_succeed) %>
            <% else %>
              <%= l(:label_failure) %>
            <% end %>
          </div>
        </div>
        <div class="scheduled-date attribute">
          <div class="label"><%=l(:field_execution_date)%></div>
          <div id="execution_date" class="value"><%= yyyymmdd_date(@test_case_execution.execution_date) %></div>
        </div>
        <div class="issue_id attribute">
          <div class="label"><%=l(:field_issue)%></div>
          <div id="issue_id" class="value">
            <% if @test_case_execution.issue %>
              <%= link_to @test_case_execution.issue, issue_path(id: @test_case_execution.issue.id) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div>
      <p><%=l(:field_comment)%></p>
      <div id="comment" class="wiki">
        <%= @test_case_execution.comment %>
      </div>
    </div>
  </div>
  <div class="attributes">
    <div>
      <p><%=l(:field_scenario)%></p>
      <pre id="scenario" class="wiki"><%= @test_case.scenario %></pre>
    </div>
    <div>
      <p><%=l(:field_expected)%></p>
      <pre id="expected" class="wiki"><%= @test_case.expected %></pre>
    </div>
  </div>
  <% if @test_case_execution.attachments.any? %>
    <hr />
    <p><strong><%=l(:label_attachment_plural)%></strong></p>
    <%= link_to_attachments @test_case_execution, :thumbnails => true %>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render :partial => 'test_case_executions/sidebar' %>
<% end %>