config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do |map|
  resources :projects do
    get 'test_cases/auto_complete', to: 'test_cases#auto_complete', as: 'auto_complete_test_cases'

    get 'test_plans/statistics', to: 'test_plans#statistics', as: 'test_plan_statistics'
    get 'test_cases/statistics', to: 'test_cases#statistics', as: 'test_case_statistics'

    match 'test_cases/context_menu', :to => 'test_cases#list_context_menu', :as => :test_case_list_context_menu, :via => [:get, :post]
    resources :test_cases do
      resources :test_case_executions
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
      #match 'context_menu', :to => 'test_cases#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
    end

    match 'test_plans/context_menu', :to => 'test_plans#list_context_menu', :as => :test_plan_list_context_menu, :via => [:get, :post]
    resources :test_plans do
      resources :test_cases do
        resources :test_case_executions
      end

      resources :test_case_executions

      post 'assign_test_case', to: 'test_plans#assign_test_case'
      delete 'assign_test_case/:id', to: 'test_plans#unassign_test_case'
      delete 'assign_test_case', to: 'test_plans#unassign_test_case'

      match 'context_menu', :to => 'test_plans#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end

    match 'test_case_executions/context_menu', :to => 'test_case_executions#list_context_menu', :as => :test_case_execution_list_context_menu, :via => [:get, :post]
    resources :test_case_executions do
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end
  end

  get 'projects/:project_id/test_cases/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseImport'},
      :as => 'new_test_cases_import'

  get 'projects/:project_id/test_plans/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestPlanImport'},
      :as => 'new_test_plans_import'

  get 'projects/:project_id/test_case_executions/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseExecutionImport'},
      :as => 'new_test_case_executions_import'
end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController

  include ApplicationsHelper

  before_action :find_project_id
  before_action :find_test_plan_id_if_given, :only => [:new, :create, :show, :edit, :index, :update, :destroy]
  before_action :find_test_case, :only => [:show, :edit, :update, :destroy]
  before_action :authorize_with_issues_permission
  before_action :find_test_cases, :only => [:list_context_menu, :bulk_edit, :bulk_update, :bulk_delete]

  before_action do
    prepare_user_candidates
    prepare_issue_status_candidates
    if @test_plan
      prepare_test_plan_candidates
    end
  end

  helper :attachments
  helper :queries
  include QueriesHelper
  helper :test_cases_queries
  include TestCasesQueriesHelper
  helper :context_menus

  # GET /projects/:project_id/test_cases
  # GET /projects/:project_id/test_plans/:test_plan_id/test_cases
  def index
    retrieve_query(TestCaseQuery, false)

    if @query.valid?
      respond_to do |format|
        @test_cases_export_limit = Setting.plugin_testcase_management["test_cases_export_limit"].to_i
        format.html do
          if @test_plan_given
            @test_case_count = @query.test_case_count(params[:test_plan_id], true)
            @test_case_pages = Paginator.new @test_case_count, per_page_option, params["page"]
            @test_cases = @query.test_cases(test_plan_id: params[:test_plan_id],
                                            offset: @test_case_pages.offset,
                                            limit: @test_case_pages.per_page).visible
            @title = html_title(l(:label_test_cases),
                                "##{@test_plan.id} #{@test_plan.name}",
                                l(:label_test_plans))
            @csv_url = project_test_plan_test_cases_path(@project, test_plan_id: params[:test_plan_id], format: "csv")
          else
            @test_case_count = @query.test_case_count(nil, true)
            @test_case_pages = Paginator.new @test_case_count, per_page_option, params["page"]
            @test_cases = @query.test_cases(offset: @test_case_pages.offset,
                                            limit: @test_case_pages.per_page).visible
            @title = html_title(l(:label_test_cases))
            @csv_url = project_test_cases_path(@project, format: "csv")
          end
        end
        format.csv do
          if @test_plan_given
            @test_cases = @query.test_cases(test_plan_id: params[:test_plan_id],
                                            limit: @test_cases_export_limit).visible
          else
            @test_cases = @query.test_cases(limit: @test_cases_export_limit).visible
          end
          send_data(query_to_csv(@test_cases, @query, params[:csv]),
                    :type => 'text/csv; header=present', :filename => 'test_cases.csv')
        end
      end
    else
      flash.now[:error] = l(:error_index_failure)
      render 'forbidden', status: :unprocessable_entity
    end
  end

  # GET /projects/:project_id/test_cases/new
  # GET /projects/:project_id/test_plans/:test_plan_id/test_cases/new
  def new
    @test_case = TestCase.new
    if params.permit(:test_plan_id)[:test_plan_id]
      @test_plan = TestPlan.find(params.permit(:test_plan_id)[:test_plan_id])
      @title = html_title(l(:label_test_case_new),
                          "##{@test_plan.id} #{@test_plan.name}",
                          l(:label_test_plans))
    else
      @test_plan = nil
      @title = html_title(l(:label_test_case_new))
    end
  end

  # POST /projects/:project_id/test_cases
  # POST /projects/:project_id/test_plans/:test_plan_id/test_cases
  def create
    unless User.current.allowed_to?(:add_issues, @project, :global => true)
      raise ::Unauthorized
    end
    begin
      @test_case = TestCase.new(:project_id => @project.id,
                                :name => test_case_params[:name],
                                :user => User.find(test_case_params[:user]),
                                :environment => test_case_params[:environment],
                                :scenario => test_case_params[:scenario],
                                :expected => test_case_params[:expected])
      @test_case.test_plans << @test_plan if @test_plan
      if params[:attachments].present?
        @test_case.save_attachments params.require(:attachments).permit!
      end
      if @test_case.valid?
        @test_case.save
        flash[:notice] = l(:notice_successful_create)
        if @test_plan
          if params[:continue]
            redirect_to new_project_test_plan_test_case_path(test_plan_id: @test_plan.id)
          else
            redirect_to project_test_plan_path(id: @test_plan.id)
          end
        else
          if params[:continue]
            redirect_to new_project_test_case_path
          else
            redirect_to project_test_case_path(id: @test_case.id)
          end
        end
      else
        render :new, status: :unprocessable_entity
      end
    rescue
      render :new, status: :unprocessable_entity
    end
  end

  # GET /projects/:project_id/test_cases/:id
  # GET /projects/:project_id/test_plans/:test_plan_id/test_cases/:id
  def show
    if @test_plan_given
      @test_case_executions = @test_case.test_case_executions_for(@test_plan)
      @title = html_title("##{@test_case.id} #{@test_case.name}",
                          l(:label_test_cases),
                          "##{@test_plan.id} #{@test_plan.name}",
                          l(:label_test_plans))
    else
      @test_case_executions = @test_case.test_case_executions
      @title = html_title("##{@test_case.id} #{@test_case.name}",
                          l(:label_test_cases))
    end
  end

  # GET /projects/:project_id/test_cases/:id/edit
  # GET /projects/:project_id/test_plans/:test_plan_id/test_cases/:id/edit
  def edit
    if @test_plan_given
      @title = html_title("#{l(:label_test_case_edit)} ##{@test_case.id}",
                          l(:label_test_cases),
                          "##{@test_plan.id} #{@test_plan.name}",
                          l(:label_test_plans))
    else
      @title = html_title("#{l(:label_test_case_edit)} ##{@test_case.id}",
                          l(:label_test_cases))
    end
  end

  # PUT /projects/:project_id/test_cases/:id
  # PUT /projects/:project_id/test_plans/:test_plan_id/test_cases/:id
  def update
    raise ::Unauthorized unless @test_case.editable?
    update_params = {
      name: test_case_params[:name],
      scenario: test_case_params[:scenario],
      expected: test_case_params[:expected],
      environment: test_case_params[:environment]
    }
    user = User.find(test_case_params[:user])
    update_params[:user_id] = user.id if user.present?
    if params[:attachments].present?
      @test_case.save_attachments params.require(:attachments).permit!
    end
    if @test_case.update(update_params)
      flash[:notice] = l(:notice_successful_update)
      if params[:test_plan_id].present?
        redirect_to project_test_plan_path(id: params[:test_plan_id])
      else
        redirect_to project_test_case_path
      end
    else
      flash.now[:error] = l(:error_update_failure)
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/:project_id/test_cases/:id
  # DELETE /projects/:project_id/test_plans/:test_plan_id/test_cases/:id
  def destroy
    raise ActiveRecord::RecordNotFound unless @test_case.visible?
    raise ::Unauthorized unless @test_case.deletable?
    begin
      if @test_case.destroy
        flash[:notice] = l(:notice_successful_delete)
        if params[:test_plan_id].present?
          redirect_to project_test_plan_path(id: params.permit(:test_plan_id)[:test_plan_id])
        else
          redirect_to project_test_cases_path
        end
      else
        flash.now[:error] = l(:error_delete_failure)
        render :show
      end
    rescue
      flash.now[:error] = l(:error_test_case_not_found)
      render 'forbidden', status: 404
    end
  end

  # GET /projects/:project_id/test_cases/auto_complete
  def auto_complete
    test_cases = []
    unless User.current.allowed_to?(:view_issues, @project, :global => true)
      render :json => test_cases
      return
    end
    q = params.permit(:term)[:term]
    test_plan_id = params.permit(:test_plan_id)[:test_plan_id]
    num = 0
    if q.present?
      begin
        num = Integer(q)
      rescue
      end
    end
    like = if Redmine::Database.postgresql?
             "ILIKE"
           else
             "LIKE"
           end
    begin
      if test_plan_id.present?
        test_cases = TestCase.visible.where.not(id: TestPlan.find(test_plan_id).test_cases.select(:id))
                       .where("projects.identifier = ? AND test_cases.name #{like} ?",
                              @project.identifier, "%#{q}%").order(id: :desc).limit(10).to_a
      end
      render :json => format_test_cases_json(test_cases)
    rescue
      render :json => test_cases
    end
  end

  # GET /projects/:project_id/test_cases/statistics
  def statistics
    return unless authorize_with_issues_permission(params[:controller], :index)
    begin
      # 1. Generate every TP - TC - TCE set
      # 2. Group by test plan id and test case id using PARTITION BY
      # 3. Filter with row number, rownum = 1 means latest execution date
      #    if same execution_date exists, larger test_case_executions.id is latest one.
      # 4. Group by test plan's user, then sum up each statistical items.
      #
      subquery = <<-SQL
                   INNER JOIN issue_statuses AS TPIS ON test_plans.issue_status_id = TPIS.id
                     AND TPIS.is_closed = '0'
                   LEFT JOIN (
                     SELECT * FROM (
                       SELECT *, row_number() OVER (
                         PARTITION BY test_plan_id, test_case_id
                         ORDER BY execution_date desc, id desc
                       ) AS rownum

app/helpers/test_cases_helper.rb
module TestCasesHelper
  include ApplicationsHelper

  def test_case_destroy_confirmation_message(test_case)
    message = "#{test_case.name}\n"
    message << l(:text_test_case_destroy_confirmation)
    message
  end

  def breadcrumb
    links = []

    if @test_plan_given
      links << link_to(l(:label_test_plans),
                       project_test_plans_path)
      links << "&#187;"
      if @test_plan
        links << link_to("##{@test_plan.id} #{@test_plan.name}",
                         project_test_plan_path(id: @test_plan.id))
        links << "&#187;"
      end
      links << ""
    elsif params[:action] != "index"
      links << link_to(l(:label_test_cases),
                       project_test_cases_path)
      links << "&#187;"
      links << ""
    end

    links.join(" ").html_safe
  end
end

app/views/test_cases/_action_menu.html.erb
<div class="contextual">
  <% if @test_plan_given %>
    <%= link_to l(:button_list),
                project_test_plan_path(id: @test_plan.id),
                class: 'icon icon-list' %>
    <%= link_to l(:button_edit), edit_project_test_plan_test_case_path,
                :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
                :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @test_case.editable? %>
    <%= link_to l(:button_delete), project_test_plan_test_case_path,
                :data => {:confirm => test_case_destroy_confirmation_message(@test_case)},
                :method => :delete, :class => 'icon icon-del' if @test_case.deletable? %>
  <% else %>
    <%= link_to l(:button_list),
                project_test_cases_path,
                class: 'icon icon-list' %>
    <%= link_to l(:button_edit), edit_project_test_case_path,
                :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
                :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @test_case.editable? %>
    <%= link_to l(:button_delete), project_test_case_path,
                :data => {:confirm => test_case_destroy_confirmation_message(@test_case)},
                :method => :delete, :class => 'icon icon-del' if @test_case.deletable? %>
  <% end %>
</div>

app/views/test_cases/_form.html.erb
<div class="box tabular">
  <% if @test_plan_given %>
    <p>
      <%= form.label :test_plan %>
      <% if @test_plan %>
        <%= @test_plan.name %>
        <%= form.hidden_field :test_plan_id, :value => @test_plan.id %>
      <% else %>
        <%= form.select :test_plan_id, @test_plan_candidates %>
      <% end %>
    </p>
  <% end %>
  <p>
    <%= form.label :test_case_name %>
    <%= form.text_field :name, size: 80, required: true, id: "name" %>
  </p>
  <p>
    <%= form.label :user %>
    <% if @test_case and @test_case.user %>
      <%= form.select :user, @user_candidates, selected: @test_case.user.id %>
    <% else %>
      <%= form.select :user, @user_candidates %>
    <% end %>
  </p>
  <p>
    <%= form.label :environment %>
    <%= form.text_field :environment, size: 80, id: "environment" %>
  </p>
  <p>
    <%= form.label :scenario %>
    <%= form.text_area :scenario, required: true, id: "scenario", cols: 60, rows: [[10, @test_case.scenario.to_s.length / 50].max, 20].min %>
  </p>
  <p>
    <%= form.label :expected %>
    <%= form.text_area :expected, required: true, id: "expected", cols: 60, rows: [[10, @test_case.expected.to_s.length / 50].max, 20].min %>
  </p>
</div>

<div class="box">
  <p>
    <%= form.label l :label_attachment_plural %>
    <%= render partial: 'attachments/form' %>
  </p>
</div>

app/views/test_cases/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<%= form_tag({}, :data => {:cm_url => project_test_case_list_context_menu_path}) do -%>
  <%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>
  <%= query_columns_hidden_tags(query) %>
  <div class="autoscroll">
  <table id="test_cases_list" class="list test_case odd-even <%= query.css_classes %>">
    <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% query.inline_columns.each do |column| %>
          <%= column_header(query, column, query_options) %>
        <% end %>
        <th class="buttons"></th>
      </tr>
    </thead>
    <tbody>
      <% test_cases.each do |test_case| -%>
        <tr id="test-case-<%= test_case.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", test_case.id, false, id: nil) %></td>
          <% query.inline_columns.each do |column| %>
            <% if [:scenario, :expected, :name].include?(column.css_classes) %>
              <%= content_tag('td', column_content(column, test_case), :class => column.css_classes, :style => "text-align: left;") %>
            <% else %>
              <%= content_tag('td', column_content(column, test_case), :class => column.css_classes) %>
            <% end %>
          <% end %>
          <td class="buttons"><%= link_to_context_menu %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  </div>
<% end -%>

<% context_menu %>

app/views/test_cases/_sidebar.html.erb
<h3><%= l(:label_testcase_management) %></h3>

<ul>
  <li><%= link_to l(:label_test_cases), project_test_cases_path %></li>
  <li><%= link_to l(:label_test_plans), project_test_plans_path %></li>
  <% if @test_plan and @test_case and @test_case.id %>
    <li><%= link_to l(:label_test_case_executions),
                    project_test_plan_test_case_test_case_executions_path(
                      test_case_id: @test_case.id,
                    ) %></li>
    <li><%= link_to l(:label_test_case_execution_new),
                    new_project_test_plan_test_case_test_case_execution_path(
                      test_case_id: @test_case.id,
                    ) %></li>
  <% elsif @test_case and @test_case.id %>
    <li><%= link_to l(:label_test_case_executions),
                    project_test_case_test_case_executions_path(
                      test_case_id: @test_case.id,
                    ) %></li>
  <% else %>
    <li><%= link_to l(:label_test_case_executions),
                    project_test_case_executions_path %></li>
  <% end %>
</ul>

<h3><%= l(:label_statistics) %></h3>

<ul>
  <li><%= link_to l(:label_test_plan_statistics), project_test_plan_statistics_path, class: 'icon icon-stats' %></li>
  <li><%= link_to l(:label_test_case_statistics), project_test_case_statistics_path, class: 'icon icon-stats' %></li>
</ul>

<%= call_hook(:view_test_cases_sidebar_bottom) %>

<% if controller.action_name == "index" %>
  <%= render_sidebar_queries(TestCaseQuery, @project) %>
  <%= call_hook(:view_test_cases_sidebar_queries_bottom) %>
<% end %>

app/views/test_cases/bulk_edit.html.erb
<h2><%= l(:label_bulk_edit_selected_test_cases) %></h2>

<% if @saved_test_cases && @unsaved_test_cases.present? %>
<div id="errorExplanation">
  <span>
    <%= l(:notice_failed_to_save_test_cases,
        :count => @unsaved_test_cases.size,
        :total => @saved_test_cases.size,
        :ids => @unsaved_test_cases.map {|i| "##{i.id}"}.join(', ')) %>
  </span>
  <ul>
  <% bulk_edit_error_messages(@unsaved_test_cases).each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<ul id="bulk-selection">
  <% @test_cases.each do |test_case| %>
    <%= content_tag 'li', link_to(test_case.name, project_test_case_path(id: test_case.id)) %>
  <% end %>
</ul>

<%= form_tag(bulk_update_project_test_cases_path(back: @back_url), :id => 'bulk_edit_form') do %>
  <%= hidden_field_tag('back_url', @back_url) %>
  <%= @test_cases.collect {|i| hidden_field_tag('ids[]', i.id, :id => nil)}.join("\n").html_safe %>
  <div class="box tabular">
    <fieldset class="attributes">
      <legend><%= l(:label_change_properties) %></legend>

      <div class="splitcontent">
        <div class="splitcontentleft">
          <% if @safe_attributes.include?('environment') -%>
          <p>
            <label for='test_case_environment'><%= l(:field_environment) %></label>
            <%= text_field_tag "test_case[environment]", nil, size:60, id: "environment" %>
          </p>
          <% end %>
        </div>
        <div class="splitcontentleft">
          <% if @safe_attributes.include?('user_id') -%>
          <p>
            <label for='test_case_user_id'><%= l(:field_user) %></label>
            <%= select_tag('test_case[user_id]',
                content_tag('option', l(:label_no_change_option), :value => '') +
            principals_options_for_select(@assignables, @test_case_params[:user_id])) %>
          </p>
          <% end %>
        </div>

        <div class="splitcontentright">
        </div>
      </div>
    </fieldset>
  </div>
  <p>
    <%= submit_tag l(:button_submit) %>
  </p>
<% end %>

<%= javascript_tag do %>
$(window).on('load', function(){
  $(document).on('change', 'input[data-disables]', function(){
    if ($(this).prop('checked')){
      $($(this).data('disables')).attr('disabled', true).val('');
    } else {
      $($(this).data('disables')).attr('disabled', false);
    }
  });
});
$(document).ready(function(){
  $('input[data-disables]').trigger('change');
});
<% end %>

app/views/test_cases/edit.html.erb
<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_case_edit)%> #<%= @test_case.id %></h2>

<%= form_with model: @test_case, url: (@test_plan_given ? project_test_plan_test_case_path : project_test_case_path) do |f| %>
  <%= render partial: 'test_cases/form', locals: {form: f} %>
  <%= f.submit l(:button_update) %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_cases/sidebar' %>
<% end %>

app/views/test_cases/forbidden.html.erb
<% if @project %>
  <% if @test_plan_given %>
    <% if @test_plan %>
      <%= link_to l(:label_back_to_lists), project_test_plan_test_cases_path %>
    <% else %>
      <%= link_to l(:label_back_to_lists), project_test_plans_path %>
    <% end %>
  <% else %>
    <%= link_to l(:label_back_to_lists), project_test_cases_path %>
  <% end %>
<% else %>
  <%= link_to l(:label_back_to_lists), projects_path %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_cases/sidebar' %>
<% end %>

app/views/test_cases/index.html.erb
<div class="contextual">
  <% if @test_plan_given %>
    <%= link_to l(:label_test_case_new),
                (@test_plan ? new_project_test_plan_test_case_path : new_project_test_plans_path),
                :class => "icon icon-add new-issue" %>
  <% else %>
    <%= link_to l(:label_test_case_new),
                 new_project_test_case_path,
                 :class => "icon icon-add new-issue" %>
  <% end %>
  <%= actions_dropdown do %>
    <% if User.current.allowed_to?(:add_test_cases, @project, :global => true) %>
      <%= link_to l(:button_import),
                  new_test_cases_import_path(:project_id => @project),
                  :class => "icon icon-import" %>
    <% end %>
    <%= link_to l(:label_test_case_statistics),
                project_test_case_statistics_path,
                :class => "icon icon-stats" %>
  <% end %>
</div>

<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_cases)%></h2>

<% if @test_plan_given %>
  <%= form_tag(project_test_plan_test_cases_path, :method => :get, :id => 'query_form') do %>
    <%= render :partial => 'queries/query_form' %>
  <% end %>
<% else %>
  <%= form_tag(project_test_cases_path, :method => :get, :id => 'query_form') do %>
    <%= render :partial => 'queries/query_form' %>
  <% end %>
<% end %>

<% if @query.valid? %>
  <% if @test_cases.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => "test_cases/list", :locals => {:test_cases => @test_cases, :query => @query} %>
    <span class="pagination"><%= pagination_links_full @test_case_pages, @test_case_count %></span>
  <% end %>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to_with_query_parameters 'CSV', {}, :onclick => "showModal('csv-export-options', '350px'); return false;" %>
<% end %>

<div id="csv-export-options" style="display:none;">
  <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
  <%= form_tag(@csv_url, :method => :get, :id => 'csv-export-form') do %>
  <%= query_as_hidden_field_tags(@query) %>
  <%= export_csv_encoding_select_tag %>
  <% if @test_case_count > @test_cases_export_limit %>
  <p class="icon icon-warning">
    <%= l(:settings_test_cases_export_limit) %>: <%= @test_cases_export_limit %>
  </p>
  <% end %>
  <p class="buttons">
    <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);", :data => { :disable_with => false } %>
    <%= link_to_function l(:button_cancel), "hideModal(this);" %>
  </p>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render :partial => 'test_cases/sidebar' %>
<% end %>

app/views/test_cases/list_context_menu.html.erb
<ul>
  <% if @test_case -%>
    <li><%= context_menu_link l(:button_edit), edit_project_test_case_path(id: @test_case.id),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>

    <li><%= link_to l(:label_deleted),
             "/projects/#{@project.identifier}/test_cases/#{@test_case.id}",
             method: :delete,
             data: { confirm: l(:text_are_you_sure) },
             title: l(:label_delete),
             class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
  <% else %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_project_test_cases_path(:ids => @test_case_ids, :back_url => @back),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>
    <% ids = @test_cases.pluck(:id).map { |id| "ids[]=#{id}" }.join("&") %>
    <li><%= link_to l(:label_deleted),
            bulk_delete_project_test_cases_path(:ids => @test_case_ids, :back_url => @back),
            method: :delete,
            data: { confirm: l(:text_are_you_sure) },
            title: l(:label_deleted),
            class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
  <% end %>
</ul>