config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do |map|
  resources :projects do
    get 'test_cases/auto_complete', to: 'test_cases#auto_complete', as: 'auto_complete_test_cases'

    get 'test_plans/statistics', to: 'test_plans#statistics', as: 'test_plan_statistics'
    get 'test_cases/statistics', to: 'test_cases#statistics', as: 'test_case_statistics'

    match 'test_cases/context_menu', :to => 'test_cases#list_context_menu', :as => :test_case_list_context_menu, :via => [:get, :post]
    resources :test_cases do
      resources :test_case_executions
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
      #match 'context_menu', :to => 'test_cases#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
    end

    match 'test_plans/context_menu', :to => 'test_plans#list_context_menu', :as => :test_plan_list_context_menu, :via => [:get, :post]
    resources :test_plans do
      resources :test_cases do
        resources :test_case_executions
      end

      resources :test_case_executions

      post 'assign_test_case', to: 'test_plans#assign_test_case'
      delete 'assign_test_case/:id', to: 'test_plans#unassign_test_case'
      delete 'assign_test_case', to: 'test_plans#unassign_test_case'

      match 'context_menu', :to => 'test_plans#show_context_menu', :as => :show_context_menu, :via => [:get, :post]
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end

    match 'test_case_executions/context_menu', :to => 'test_case_executions#list_context_menu', :as => :test_case_execution_list_context_menu, :via => [:get, :post]
    resources :test_case_executions do
      collection do
        get 'bulk_edit'
        post 'bulk_update'
        delete 'bulk_delete'
      end
    end
  end

  get 'projects/:project_id/test_cases/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseImport'},
      :as => 'new_test_cases_import'

  get 'projects/:project_id/test_plans/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestPlanImport'},
      :as => 'new_test_plans_import'

  get 'projects/:project_id/test_case_executions/imports/new',
      :to => 'imports#new',
      :defaults => {:type => 'TestCaseExecutionImport'},
      :as => 'new_test_case_executions_import'
end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
  include Redmine::SafeAttributes
  include TestCaseManagement::SafeAttributes
  include TestCaseManagement::InheritIssuePermissions

  belongs_to :user
  belongs_to :project
  has_many :test_case_test_plans, dependent: :destroy
  has_many :test_plans, through: :test_case_test_plans
  has_many :test_case_executions, dependent: :destroy
  acts_as_attachable

  validates :name, presence: true
  validates :scenario, presence: true
  validates :expected, presence: true
  validates :user, presence: true
  validates :project, presence: true

  validates_associated :test_case_executions

  validate :owned_only_by_visible_user

  safe_attributes(
    "project_id",
    "user_id",
    "name",
    "environment",
    "scenario",
    "expected",
    :if => lambda {|instance, user| instance.new_record? || instance.attributes_editable?(user)})

  def safe_attribute_names(user=nil)
    names = super
    if new_record?
      names |= %w(project_id)
    end
    names
  end

  scope :visible, (lambda do |*args|
    joins(:project).
    where(TestCaseManagement::InheritIssuePermissions.visible_condition(args.shift || User.current, *args))
  end)

  scope :with_latest_result, (lambda do |test_plan_or_id=nil, for_count=false|
    test_plan_id = test_plan_or_id
    test_plan_id = test_plan_or_id.id if test_plan_or_id.is_a?(TestPlan)
    test_plan_id = nil unless test_plan_id.is_a?(Integer)

    scope = all
    conditions = {}
    if test_plan_id
      scope = scope.
        joins(:test_case_test_plans)
      conditions["test_case_test_plans.test_plan_id"] = test_plan_id
    end

    scope = scope.
    joins(<<-"SQL"
      LEFT OUTER JOIN
        (SELECT *
           FROM (SELECT *,
                        ROW_NUMBER()
                          OVER (PARTITION BY test_case_id
                                ORDER BY execution_date DESC, id DESC)
                          AS row_number_per_test_case_id
                   FROM test_case_executions
                   #{ test_plan_id ? sanitize_sql_array(['WHERE test_plan_id = ?', test_plan_id]) : '' })
                 AS tce_with_row_number
          WHERE row_number_per_test_case_id = 1) AS tce
        ON tce.test_case_id = test_cases.id
        #{ test_plan_id ? 'AND tce.test_plan_id = test_case_test_plans.test_plan_id' : '' }
SQL
    ).
    where(conditions)
    # Avoid syntax error with count()
    if for_count
      if Redmine::Database.postgresql?
        scope.select("test_cases.*")
      else
        scope.select("*")
      end
    else
      scope.select(<<-SQL
        test_cases.*,
        tce.id AS latest_execution_id,
        tce.result AS latest_result,
        tce.execution_date AS latest_execution_date
SQL
    )
    end
  end)

  class << self
    def find_with_latest_result(id, options={})
      with_latest_result(options[:test_plan] || options[:test_plan_id]).find(id)
    end
  end

  # attributes based on most recently executed result
  def latest_result
    value = attributes["latest_result"]
    if value.is_a?(Integer) # SQLite
      attributes["latest_result"] = value == 1
    else # PostgreSQL and others
      value
    end
  end

  def latest_execution_date
    value = attributes["latest_execution_date"]
    if value.is_a?(String) # SQLite
      attributes["latest_execution_date"] = Time.parse(value)
    else # PostgreSQL and others
      value
    end
  end

  def latest_test_case_execution
    if attributes["latest_execution_id"]
      TestCaseExecution.find(attributes["latest_execution_id"])
    else
      nil
    end
  end

  def test_case_executions_for(test_plan=self.test_plan)
    conditions = {test_case: self}
    if test_plan
      if test_plan.is_a?(TestPlan)
        conditions[:test_plan] = test_plan
      else
        conditions[:test_plan_id] = test_plan
      end
    end
    TestCaseExecution
      .where(conditions)
  end


  def attachments_visible?(user=User.current)
    visible?(user)
  end

  def attachments_editable?(user=User.current)
    editable?(user)
  end

  def attachments_deletable?(user=User.current)
    deletable?(user)
  end


  # Workaround for functional tests.
  # This should be removed after we completely migrate to test_plan-independent design.
  def test_plan
    test_plans.first
  end
end

app/controllers/test_plans_controller.rb
class TestPlansController < ApplicationController

  include ApplicationsHelper

  before_action :find_project_id
  before_action :find_test_plan, :only => [:show, :edit, :update, :destroy]
  before_action :find_test_plan_id, :only => [:assign_test_case, :unassign_test_case]
  before_action :find_test_cases, :only => [:show_context_menu, :unassign_test_case]
  before_action :authorize_with_issues_permission
  before_action :find_test_plans, :only => [:list_context_menu, :bulk_edit, :bulk_update, :bulk_delete]

  before_action do
    prepare_issue_status_candidates
    prepare_user_candidates
  end

  helper :queries
  include QueriesHelper
  helper :test_plans_queries
  include TestPlansQueriesHelper
  helper :context_menus

  # GET /projects/:project_id/test_plans
  def index
    retrieve_query(TestPlanQuery, false)

    if @query.valid?
      respond_to do |format|
        @test_plans_export_limit = Setting.plugin_testcase_management["test_plans_export_limit"].to_i
        format.html do
          @test_plan_count = @query.test_plan_count
          @test_plan_pages = Paginator.new @test_plan_count, per_page_option, params["page"]
          test_plans_params = {offset: @test_plan_pages.offset,
                               limit: @test_plan_pages.per_page}
          if params[:test_case_id].present?
            test_plans_params[:test_case_id] = params[:test_case_id]
          end
          @test_plans = @query.test_plans(test_plans_params).visible
          @title = html_title(l(:label_test_plans))
          @csv_url = project_test_plans_path(@project, format: "csv")
        end
        format.csv do
          test_plans_params = {limit: @test_plans_export_limit}
          if params[:test_case_id].present?
            test_plans_params[:test_case_id] = params[:test_case_id]
          end
          @test_plans = @query.test_plans(test_plans_params).visible
          send_data(query_to_csv(@test_plans, @query, params[:csv]),
                    :type => 'text/csv; header=present', :filename => 'test_plans.csv')
        end
      end
    else
      flash.now[:error] = l(:error_index_failure)
      render 'forbidden', status: :unprocessable_entity
    end
  end

  # GET /projects/:project_id/test_plans/:id
  def show
    @test_case_test_plan = TestCaseTestPlan.new

    @title = html_title("##{@test_plan.id} #{@test_plan.name}", l(:label_test_plans))

    retrieve_query(TestCaseQuery, false)
    if @query.valid?
      @test_case_count = @query.test_case_count(params[:id], true)
      @test_case_pages = Paginator.new @test_case_count, per_page_option, params["page"]
      @test_cases = @query.test_cases(test_plan_id: params[:id],
                                      offset: @test_case_pages.offset,
                                      limit: @test_case_pages.per_page).visible
    end
  end

  # GET /projects/:project_id/test_plans/:id/edit
  def edit
    @title = html_title("#{l(:label_test_plan_edit)} ##{@test_plan.id}")
  end

  # PUT /projects/:project_id/test_plans/:id
  def update
    raise ::Unauthorized unless @test_plan.editable?
    update_params = {}
    update_params[:name] = test_plan_params[:name]
    update_params[:begin_date] = test_plan_params[:begin_date]
    update_params[:end_date] = test_plan_params[:end_date]
    update_params[:estimated_bug] = test_plan_params[:estimated_bug]
    if test_plan_params[:user].present?
      user = User.find(test_plan_params[:user])
      update_params[:user_id] = user.id
    end
    if test_plan_params[:issue_status].present?
      issue_status = IssueStatus.find(test_plan_params[:issue_status])
      update_params[:issue_status_id] = issue_status.id
    end
    if @test_plan.update(update_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to project_test_plan_path
    else
      flash.now[:error] = l(:error_update_failure)
      render :edit
    end
  end

  # GET /projects/:project_id/test_plans/new
  def new
    @test_plan = TestPlan.new
    @title = html_title(l(:label_test_plan_new))
  end

  # POST /projects/:project_id/test_plans
  def create
    unless User.current.allowed_to?(:add_issues, @project, :global => true)
      raise ::Unauthorized
    end
    @test_plan = TestPlan.new(:name => test_plan_params[:name],
                              :begin_date => test_plan_params[:begin_date],
                              :end_date => test_plan_params[:end_date],
                              :user => User.find(test_plan_params[:user].to_i),
                              :estimated_bug => test_plan_params[:estimated_bug],
                              :issue_status => IssueStatus.find(test_plan_params[:issue_status].to_i),
                              :project_id => @project.id)
    if @test_plan.valid?
      @test_plan.save
      flash[:notice] = l(:notice_successful_create)
      if params[:continue]
        redirect_to new_project_test_plan_path(@project)
      else
        redirect_to project_test_plan_path(:id => @test_plan.id)
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /projects/:project_id/test_plans/:id
  def destroy
    raise ActiveRecord::RecordNotFound unless @test_plan.visible?
    raise ::Unauthorized unless @test_plan.deletable?
    begin
      if @test_plan.destroy
        flash[:notice] = l(:notice_successful_delete)
        redirect_to project_test_plans_path
      else
        flash.now[:error] = l(:error_delete_failure)
        render :show
      end
    rescue
      flash.now[:error] = l(:error_test_plan_not_found)
      render 'forbidden', status: 404
    end
  end

  # POST /projects/:project_id/test_plans/:test_plan_id/assign_test_case
  def assign_test_case
    begin
      @test_case = TestCase.find(params.require(:test_case_test_plan).permit(:test_case_id)[:test_case_id])
      raise ActiveRecord::RecordNotFound unless @test_case.visible?
      raise ActiveRecord::RecordNotFound unless @test_plan.visible?
      @test_case_test_plan = TestCaseTestPlan.where(test_plan: @test_plan,
                                                    test_case: @test_case).first
      unless @test_case_test_plan
        @test_case_test_plan = TestCaseTestPlan.new(test_plan: @test_plan,
                                                    test_case: @test_case)
        if @test_case_test_plan.save
          flash[:notice] = l(:notice_successful_update)
        end
      end
      redirect_to project_test_plan_path(id: @test_plan.id)
    rescue ActiveRecord::RecordNotFound
      flash[:error] = l(:error_test_case_not_found) unless @test_case
      redirect_to project_test_plan_path(id: @test_plan.id)
    rescue
      render 'forbidden', status: 404
    end
  end

  # DELETE /projects/:project_id/test_plans/:test_plan_id/assign_test_case/:id
  # DELETE /projects/:project_id/test_plans/:test_plan_id/assign_test_case/?ids[]=ID1&ids[]=ID2 ...
  def unassign_test_case
    begin
      raise ActiveRecord::RecordNotFound unless @test_cases.all?(&:visible?)
      raise ActiveRecord::RecordNotFound unless @test_plan.visible?
      @test_cases.each do |test_case|
        @test_case_test_plan = TestCaseTestPlan.where(test_plan: @test_plan,
                                                      test_case: test_case).first
        if @test_case_test_plan
          @test_case_test_plan.destroy
          # FIXME: unassign without full rendering, use remote XHR
          flash[:notice] = l(:notice_successful_delete)
        end
      end
      redirect_to project_test_plan_path(id: @test_plan.id)
    rescue
      render 'forbidden', status: 404
    end
  end

  # GET /projects/:project_id/test_plans/statistics
  def statistics
    begin
      #
      # 1. Generate every TP - TC - TCE set
      # 2. Group by test plan id and test case id using PARTITION BY
      # 3. Filter with row number, rownum = 1 means latest execution date
      #    if same execution_date exists, larger test_case_executions.id is latest one.
      #
      join_query = <<-SQL
                      LEFT JOIN (
                        SELECT * FROM (
                          SELECT *, row_number() OVER (
                            PARTITION BY test_plan_id, test_case_id
                            ORDER BY execution_date desc, id desc
                          ) AS rownum
                          FROM test_case_executions
                        ) AS TCE
                        WHERE TCE.rownum = 1
                        ) AS TPTCTCE
                          ON TPTCTCE.test_plan_id = test_case_test_plans.test_plan_id 
                          AND TPTCTCE.test_case_id  = test_case_test_plans.test_case_id 
                      LEFT JOIN issues ON TPTCTCE.issue_id = issues.id
                      LEFT JOIN issue_statuses AS TCEIS ON TCEIS.id = issues.status_id
SQL
      select_query = <<-SQL
                      test_plans.id, test_plans.name, test_plans.user_id, test_plans.estimated_bug,
                      SUM(CASE WHEN TPTCTCE.result IS NULL THEN 1 ELSE 0 END) AS count_not_executed,
                      SUM(CASE WHEN TPTCTCE.result = '1' THEN 1 ELSE 0 END) AS count_succeeded,
                      SUM(CASE WHEN TPTCTCE.result = '0' THEN 1 ELSE 0 END) AS count_failed,
                      SUM(CASE WHEN issues.id IS NOT NULL THEN 1 ELSE 0 END) AS detected_bug,
                      SUM(CASE WHEN TCEIS.is_closed = '1' THEN 1 ELSE 0 END) AS fixed_bug,
                      SUM(CASE WHEN TCEIS.is_closed = '0' AND issues.id IS NOT NULL THEN 1 ELSE 0 END) AS remained_bug
SQL
      @test_plans = TestPlan.joins(:test_cases)
                      .joins(join_query)
                      .where(project: @project)
                      .group(:id)
                      .select(select_query)
                      .order(id: :desc)
      @title = html_title(l(:label_test_plan_statistics))
      render :statistics
    rescue
      render 'forbidden', status: 404
    end
  end

app/helpers/test_plans_helper.rb
module TestPlansHelper
  include ApplicationsHelper

  def test_plan_destroy_confirmation_message(test_plan)
    message = "#{test_plan.name}\n"
    message << l(:text_test_plan_destroy_confirmation)
    message
  end

  def breadcrumb
    links = []

    links << link_to(l(:label_test_plans),
                     project_test_plans_path)
    links << "&#187;"
    links << ""

    links.join(" ").html_safe
  end
end

app/views/test_plans/_action_menu.html.erb
<div class="contextual">
<%= link_to l(:button_list), project_test_plans_path,
            :class => 'icon icon-list', :accesskey => accesskey(:list) %>
<%= link_to l(:button_edit), edit_project_test_plan_path,
            :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
            :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @test_plan.editable? %>
<%= link_to l(:button_delete), project_test_plan_path,
            :data => {:confirm => test_plan_destroy_confirmation_message(@test_plan)},
            :method => :delete, :class => 'icon icon-del' if @test_plan.deletable? %>
</div>

app/views/test_plans/_list.html.erb
<% query_options = nil unless defined?(query_options) %>
<% query_options ||= {} %>

<%= form_tag({}, :data => {:cm_url => project_test_plan_list_context_menu_path}) do -%>
  <%= hidden_field_tag 'back_url', url_for(:params => request.query_parameters), :id => nil %>
  <%= query_columns_hidden_tags(query) %>
  <div class="autoscroll">
  <table id="test_plans_list" class="list test_plan odd-even <%= query.css_classes %>">
    <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
              title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% query.inline_columns.each do |column| %>
          <%= column_header(query, column, query_options) %>
        <% end %>
        <th class="buttons"></th>
      </tr>
    </thead>
    <tbody>
      <% test_plans.each do |test_plan| -%>
        <tr id="test-plan-<%= test_plan.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", test_plan.id, false, id: nil) %></td>
          <% query.inline_columns.each do |column| %>
            <%= content_tag('td', column_content(column, test_plan), :class => column.css_classes) %>
          <% end %>
          <td class="buttons"><%= link_to_context_menu %></td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  </div>
<% end -%>

<% context_menu %>

app/views/test_plans/_sidebar.html.erb
<h3><%= l(:label_testcase_management) %></h3>

<ul>
  <li><%= link_to l(:label_test_cases), project_test_cases_path %></li>
  <li><%= link_to l(:label_test_plans), project_test_plans_path %></li>
  <% if @test_case %>
    <li><%= link_to l(:label_test_case_executions),
                    project_test_case_test_case_executions_path(
                      test_case_id: @test_case.id,
                    ) %></li>
  <% else %>
    <li><%= link_to l(:label_test_case_executions),
                    project_test_case_executions_path %></li>
  <% end %>
</ul>

<h3><%= l(:label_statistics) %></h3>

<ul>
  <li><%= link_to l(:label_test_plan_statistics), project_test_plan_statistics_path, class: 'icon icon-stats' %></li>
  <li><%= link_to l(:label_test_case_statistics), project_test_case_statistics_path, class: 'icon icon-stats' %></li>
</ul>

<%= call_hook(:view_test_plans_sidebar_bottom) %>

<% if controller.action_name == "index" %>
  <%= render_sidebar_queries(TestPlanQuery, @project) %>
  <%= call_hook(:view_test_plans_sidebar_queries_bottom) %>
<% end %>

app/views/test_plans/_test_case_assignment.html.erb
<p>
  <%= form.label :test_case %>
  <%= form.text_field :test_case_id,
                      size: 10,
                      required: true,
                      id: 'test_case_id',
                      title: l(:test_case_assignment_tooltip) %>
  <%= submit_tag l(:button_add) %>
  <%= link_to_function l(:button_cancel), '$("#assign-test-case-form").hide();' %>
</p>

<%= javascript_tag "observeAutocompleteField('test_case_id', '#{escape_javascript project_auto_complete_test_cases_path(project_id: @project, test_plan_id: @test_plan.id)}')" %>

app/views/test_plans/edit.html.erb
<h2 class="inline-flex"><%= breadcrumb %><%=l(:label_test_plan_edit)%> #<%= @test_plan.id %></h2>

<%= form_with model: @test_plan, url: project_test_plan_path do |f| %>
  <%= render partial: 'test_plans/form', locals: {form: f} %>
  <%= f.submit l(:button_update) %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_plans/sidebar' %>
<% end %>

app/views/test_plans/forbidden.html.erb
<% if @project %>
  <%= link_to l(:label_back_to_lists), project_test_plans_path %>
<% else %>
  <%= link_to l(:label_back_to_lists), projects_path %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'test_plans/sidebar' %>
<% end %>

app/views/test_plans/list_context_menu.html.erb
<ul>
  <% if @test_plan -%>
    <li><%= context_menu_link l(:button_edit), edit_project_test_plan_path(id: @test_plan.id),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>

    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_status) %></a>
      <ul>
        <% IssueStatus.all.each do |status| -%>
          <li><%= context_menu_link status.name, bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'issue_status_id' => status}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
        <% end -%>
      </ul>
    </li>

    <% if @test_plan %>
      <li><%= link_to l(:button_delete),
              "/projects/#{@project.identifier}/test_plans/#{@test_plan.id}",
              method: :delete,
              data: { confirm: l(:text_are_you_sure) },
              title: l(:button_delete),
              class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
    <% end %>
  <% else %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_project_test_plans_path(:ids => @test_plan_ids, :back_url => @back),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>
    <li class="folder">
      <a href="#" class="submenu"><%= l(:field_status) %></a>
      <ul>
        <% IssueStatus.all.each do |status| -%>
          <li><%= context_menu_link status.name, bulk_update_project_test_plans_path(:ids => @test_plan_ids, :test_plan => {'issue_status_id' => status}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
        <% end -%>
      </ul>
    </li>
    <% ids = @test_plans.pluck(:id).map { |id| "ids[]=#{id}" }.join("&") %>
    <li><%= link_to l(:button_delete),
            bulk_delete_project_test_plans_path(:ids => @test_plan_ids, :back_url => @back),
            method: :delete,
            data: { confirm: l(:text_are_you_sure) },
            title: l(:button_delete),
            class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
  <% end %>
</ul>

app/views/test_plans/show_context_menu.html.erb
<ul>
  <% if @test_case -%>
    <li><%= context_menu_link l(:button_edit), edit_project_test_plan_test_case_path(id: @test_case.id),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>
    <% if @test_case.test_plan %>
      <li><%= link_to l(:label_relation_delete),
              "/projects/#{@project.identifier}/test_plans/#{@test_case.test_plan.id}/assign_test_case/#{@test_case.id}",
              method: :delete,
              data: { confirm: l(:text_are_you_sure) },
              title: l(:label_relation_delete),
              class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
    <% end %>
  <% else %>
    <li><%= context_menu_link l(:button_edit), bulk_edit_project_test_cases_path(:ids => @test_case_ids, :back_url => @back),
            :class => 'icon icon-edit', :disabled => !@can[:edit] %></li>
    <% if @safe_attributes.include?("user_id") && @assignables.present? -%>
      <li class="folder">
        <a href="#" class="submenu"><%= l(:field_user) %></a>
        <ul>
          <% if @assignables.include?(User.current) %>
          <li><%= context_menu_link "<< #{l(:label_me)} >>", bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => User.current},
            :back_url => @back), :method => :post, :disabled => !@can[:edit] %></li>
          <% end %>
          <% @assignables.each do |u| -%>
          <li><%= context_menu_link u.name, bulk_update_project_test_cases_path(:ids => @test_case_ids, :test_case => {'user_id' => u}, :back_url => @back),
            :method => :post, :disabled => !@can[:edit] %></li>
          <% end -%>
        </ul>
      </li>
    <% end %>
    <% ids = @test_cases.pluck(:id).map { |id| "ids[]=#{id}" }.join("&") %>
    <li><%= link_to l(:label_relation_delete),
            "/projects/#{@project.identifier}/test_plans/#{@test_cases.first.test_plan.id}/assign_test_case/?#{ids}",
            method: :delete,
            data: { confirm: l(:text_are_you_sure) },
            title: l(:label_relation_delete),
            class: 'icon icon-link-break', disabled: !@can[:edit] %></li>
  <% end %>
</ul>